version: 1.0.{build}
install:
- ps: cmd /c npm install
build_script:
- ps: |
    $newContent = (Get-Content ./views/index.pug).Replace("#{title}", "#{title}-$env:APPVEYOR_BUILD_NUMBER")

    Set-Content -Value $newContent -Path ./views/index.pug

    7z a awsEbNodeApp.zip views/* app.js package.json routes/* public/* bin/*
for:
- 
  branches:
    only: 
     - \no-deploy\
     
  version: 1.0.{build}-{branch}
  do_not_increment_build_number: true
